# Generated by Django 3.2.9 on 2021-12-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_rename_picture_userprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
